name: CICD
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  calc-variables:
    if: github.ref_type == 'tag' || github.ref_name == 'main'
    uses: ./.github/workflows/_calc-variables.yml

  test:
    uses: ./.github/workflows/_test.yml
    secrets: inherit

  codeql:
    if: ${{ github.ref_type=='tag' || github.ref_name=='main' }}
    uses: ./.github/workflows/_codeql.yml

  docfx:
    needs: [test, codeql]
    uses: ./.github/workflows/_docfx.yml
    secrets: inherit

  nuget:
    if: ${{ github.ref_type=='tag' || github.ref_name=='main' }}
    needs: [calc-variables, test, codeql]
    uses: ./.github/workflows/_nuget.yml
    secrets: inherit
    with:
      package-version: ${{ needs.calc-variables.outputs.package-version }}
      packages-directory: ${{ needs.calc-variables.outputs.packages-directory }}

  create-release:
    if: ${{ github.ref_type=='tag' || github.ref_name=='main' }}
    needs: [calc-variables, nuget]
    uses: ./.github/workflows/_create-release.yml
    with:
      tag-name: ${{ github.tag_name || needs.calc-variables.outputs.version }}
      version: ${{ needs.calc-variables.outputs.version }}
